// ============================================================
// CYBERSECURITY INTELLIGENCE AGGREGATOR — FINAL v3
// Google Apps Script → Google Doc → NotebookLM
// ============================================================
// SETUP:
//  
//   1. Run → runCyberSecAggregator (authorize when prompted)
//   2. Run createDailyTrigger() once to automate daily at 6am Sydney
// ============================================================

const CONFIG = {
  GOOGLE_API_KEY:  'Az***************',
  MEDIASTACK_KEY:  'ae***************', 

  DOC_NAME: 'CyberSec Intelligence Report',

  MAX_CVE_RESULTS:     20,
  MAX_YOUTUBE_RESULTS: 12,

  CVE_LOOKBACK_DAYS:  7,
  NEWS_LOOKBACK_DAYS: 3,
};


// ============================================================
// MAIN ENTRY POINT
// ============================================================
function runCyberSecAggregator() {
  Logger.log('Starting CyberSec Aggregator v3...');

  const doc  = getOrCreateDoc(CONFIG.DOC_NAME);
  const body = doc.getBody();
  body.clear();

  const timestamp = new Date().toLocaleString('en-AU', { timeZone: 'Australia/Sydney' });

  const header = body.appendParagraph('CYBERSECURITY INTELLIGENCE REPORT');
  header.setHeading(DocumentApp.ParagraphHeading.HEADING1);
  header.setBold(true);

  body.appendParagraph('Auto-generated by CyberSecAggregator v3 · ' + timestamp);
  body.appendParagraph('Sources: NIST NVD · CISA KEV · GDELT · Google News · arXiv · MediaStack · YouTube · MITRE ATT&CK · Hacker News');
  body.appendHorizontalRule();

  fetchNistCVEs(body);
  fetchCVEHistory(body);
  fetchCISAKEV(body);
  fetchGDELT(body);
  fetchGoogleNewsRSS(body);
  fetchArXiv(body);
  fetchMediaStack(body);
  fetchYouTube(body);
  fetchMitreAttack(body);
  fetchHackerNews(body);

  body.appendHorizontalRule();
  body.appendParagraph('END OF REPORT — ' + timestamp);

  doc.saveAndClose();
  Logger.log('✅ Report complete. Doc URL: ' + doc.getUrl());
}


// ============================================================
// SECTION 1 — NIST NVD: Recent CVEs
// ============================================================
function fetchNistCVEs(body) {
  appendSectionHeader(body, '1 · NIST NVD — Recent CVEs (Last ' + CONFIG.CVE_LOOKBACK_DAYS + ' Days)');

  const endDate   = getNistDate(0);
  const startDate = getNistDate(CONFIG.CVE_LOOKBACK_DAYS);

  const url = 'https://services.nvd.nist.gov/rest/json/cves/2.0'
    + '?pubStartDate=' + startDate
    + '&pubEndDate='   + endDate
    + '&resultsPerPage=' + CONFIG.MAX_CVE_RESULTS;

  const raw = safeGet(url, {
    'User-Agent': 'CyberSecAggregator/3.0 (Google Apps Script)',
    'Accept': 'application/json'
  });

  if (!raw) {
    appendItem(body, '⚠ Could not fetch NIST CVE data. May be rate-limiting — try again in 30 seconds.');
    return;
  }

  let data;
  try { data = JSON.parse(raw); } catch(e) {
    appendItem(body, '⚠ CVE parse error: ' + e.message);
    return;
  }

  const vulns = data.vulnerabilities || [];
  if (vulns.length === 0) {
    appendItem(body, 'No new CVEs published in the last ' + CONFIG.CVE_LOOKBACK_DAYS + ' days.');
    return;
  }

  vulns.forEach(function(v) {
    const cve      = v.cve;
    const id       = cve.id || 'UNKNOWN';
    const descObj  = (cve.descriptions || []).find(function(d){ return d.lang === 'en'; });
    const descText = descObj ? descObj.value.substring(0, 280) : 'No description available';

    let score = 'N/A';
    if (cve.metrics) {
      if (cve.metrics.cvssMetricV31 && cve.metrics.cvssMetricV31[0])
        score = cve.metrics.cvssMetricV31[0].cvssData.baseScore;
      else if (cve.metrics.cvssMetricV30 && cve.metrics.cvssMetricV30[0])
        score = cve.metrics.cvssMetricV30[0].cvssData.baseScore;
      else if (cve.metrics.cvssMetricV2 && cve.metrics.cvssMetricV2[0])
        score = cve.metrics.cvssMetricV2[0].cvssData.baseScore;
    }

    const severity = score !== 'N/A' ? getSeverityLabel(parseFloat(score)) : '';
    appendItem(body, '[' + id + '] CVSS ' + score + ' ' + severity + '\n  ' + descText);
  });
}


// ============================================================
// SECTION 2 — NIST CVE Change History
// ============================================================
function fetchCVEHistory(body) {
  appendSectionHeader(body, '2 · NIST NVD — CVE Change History (Last 3 Days)');

  const endDate   = getNistDate(0);
  const startDate = getNistDate(3);

  const url = 'https://services.nvd.nist.gov/rest/json/cvehistory/2.0'
    + '?changeStartDate=' + startDate
    + '&changeEndDate='   + endDate
    + '&resultsPerPage=15';

  const raw = safeGet(url, {
    'User-Agent': 'CyberSecAggregator/3.0 (Google Apps Script)',
    'Accept': 'application/json'
  });

  if (!raw) {
    appendItem(body, '⚠ Could not fetch CVE history. May be rate-limited — wait 30s and retry.');
    return;
  }

  let data;
  try { data = JSON.parse(raw); } catch(e) {
    appendItem(body, '⚠ History parse error: ' + e.message);
    return;
  }

  const changes = data.cveChanges || [];
  if (changes.length === 0) {
    appendItem(body, 'No CVE changes in the last 3 days.');
    return;
  }

  changes.forEach(function(c) {
    const change  = c.change;
    const id      = change.cveId || 'UNKNOWN';
    const types   = (change.details || []).map(function(d){ return d.type; }).join(', ') || 'Unknown';
    const created = (change.created || '').substring(0, 10);
    appendItem(body, '[' + id + '] Changed: ' + types + ' on ' + created);
  });
}


// ============================================================
// SECTION 3 — CISA KEV: Actively Exploited Vulnerabilities
// ============================================================
function fetchCISAKEV(body) {
  appendSectionHeader(body, '3 · CISA KEV — Actively Exploited Vulnerabilities');

  const rssRaw = safeGet('https://kevin.gtfkd.com/rss');
  if (rssRaw) {
    const items = rssRaw.match(/<item>([\s\S]*?)<\/item>/g) || [];
    if (items.length > 0) {
      items.slice(0, 15).forEach(function(item) {
        const title = (
          item.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/) ||
          item.match(/<title>(.*?)<\/title>/) || []
        )[1] || '';

        const rawDesc = (
          item.match(/<description><!\[CDATA\[([\s\S]*?)\]\]><\/description>/) ||
          item.match(/<description>([\s\S]*?)<\/description>/) || []
        )[1] || '';

        const decoded = decodeHtmlEntities(rawDesc);
        const clean   = stripHtmlTags(decoded).replace(/\s+/g, ' ').trim().substring(0, 220);
        appendItem(body, (title ? title + ' — ' : '') + clean);
      });
      return;
    }
  }

  // Fallback: CISA direct JSON
  const jsonRaw = safeGet('https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json');
  if (!jsonRaw) { appendItem(body, '⚠ Could not fetch CISA KEV data.'); return; }

  let data;
  try { data = JSON.parse(jsonRaw); } catch(e) {
    appendItem(body, '⚠ CISA parse error: ' + e.message);
    return;
  }

  const vulns = (data.vulnerabilities || []).slice(-15).reverse();
  vulns.forEach(function(v) {
    appendItem(body,
      '[' + v.cveID + '] ' + v.vulnerabilityName
      + '\n  ' + (v.shortDescription || '').substring(0, 220)
    );
  });
}


// ============================================================
// SECTION 4 — GDELT: Global Cybersecurity Media Events
// ============================================================
function fetchGDELT(body) {
  appendSectionHeader(body, '4 · GDELT — Global Cybersecurity Media Events');

  const queries = [
    'cybersecurity+hacking',
    'ransomware+attack',
    'data+breach+malware',
    'nation+state+cyber',
  ];

  let totalFetched = 0;

  queries.forEach(function(q) {
    if (totalFetched >= 16) return;

    const url = 'https://api.gdeltproject.org/api/v1/search_ftxtsearch/search_ftxtsearch'
      + '?query=' + q
      + '&output=artlist'
      + '&sort=datedesc'
      + '&maxrecords=4';

    const raw = safeGet(url);
    if (!raw) return;

    const lines = raw.split('\n').filter(function(l){ return l.trim().length > 0; });
    lines.slice(0, 4).forEach(function(line) {
      const parts = line.split('\t');
      if (parts.length >= 3) {
        const date   = (parts[0] || '').substring(0, 8);
        const title  = (parts[2] || parts[1] || 'Untitled').trim();
        const domain = (parts[3] || '').trim();
        if (title && title.length > 5) {
          appendItem(body, '[' + date + '] ' + title + (domain ? ' (' + domain + ')' : ''));
          totalFetched++;
        }
      }
    });
  });

  if (totalFetched === 0) {
    appendItem(body, '⚠ GDELT returned no results. This is intermittent — will retry on next run.');
  }
}


// ============================================================
// SECTION 5 — Google News RSS
// ============================================================
function fetchGoogleNewsRSS(body) {
  appendSectionHeader(body, '5 · Google News RSS — Cybersecurity Headlines');

  const queries = [
    { term: 'cybersecurity+attack',      label: 'General' },
    { term: '"data+breach"',             label: 'Data Breach' },
    { term: 'ransomware',                label: 'Ransomware' },
    { term: '"zero+day"+vulnerability',  label: 'Zero-Day' },
    { term: 'malware+attack',            label: 'Malware' },
    { term: 'APT+nation+state+hacking',  label: 'Nation-State' },
  ];

  queries.forEach(function(q) {
    const url = 'https://news.google.com/rss/search?q=' + q.term + '&hl=en-AU&gl=AU&ceid=AU:en';
    const raw = safeGet(url);
    if (!raw) return;

    const items = raw.match(/<item>([\s\S]*?)<\/item>/g) || [];
    items.slice(0, 4).forEach(function(item) {
      const title   = (item.match(/<title>(.*?)<\/title>/)     || [])[1] || '';
      const pubDate = (item.match(/<pubDate>(.*?)<\/pubDate>/) || [])[1] || '';
      const clean   = title.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').trim();
      if (clean) appendItem(body, '[' + q.label + ' · ' + pubDate.substring(0, 16) + '] ' + clean);
    });
  });
}


// ============================================================
// SECTION 6 — arXiv: Cybersecurity Research Papers
// ============================================================
function fetchArXiv(body) {
  appendSectionHeader(body, '6 · arXiv — Latest Cybersecurity Research Papers');

  const searches = [
    { q: 'cat:cs.CR+AND+ransomware',                   label: 'Ransomware' },
    { q: 'cat:cs.CR+AND+intrusion+detection',          label: 'IDS/IPS' },
    { q: 'cat:cs.CR+AND+malware+classification',       label: 'Malware Analysis' },
    { q: 'cat:cs.CR+AND+vulnerability+detection',      label: 'Vulnerability' },
    { q: 'cat:cs.CR+AND+adversarial+machine+learning', label: 'Adversarial ML' },
    { q: 'cat:cs.CR+AND+phishing',                     label: 'Phishing' },
  ];

  searches.forEach(function(s) {
    const url = 'http://export.arxiv.org/api/query'
      + '?search_query=' + s.q
      + '&start=0&max_results=2&sortBy=submittedDate&sortOrder=descending';

    const raw = safeGet(url);
    if (!raw) return;

    const entries = raw.match(/<entry>([\s\S]*?)<\/entry>/g) || [];
    entries.forEach(function(entry) {
      const title     = ((entry.match(/<title>([\s\S]*?)<\/title>/)     || [])[1] || '').trim();
      const summary   = ((entry.match(/<summary>([\s\S]*?)<\/summary>/) || [])[1] || '').trim();
      const published = ((entry.match(/<published>(.*?)<\/published>/)  || [])[1] || '').substring(0, 10);
      const authorMatches = entry.match(/<name>(.*?)<\/name>/g) || [];
      const authors = authorMatches
        .slice(0, 3)
        .map(function(a){ return a.replace(/<\/?name>/g, ''); })
        .join(', ');

      if (title && title !== 'Error') {
        appendItem(body,
          '[arXiv · ' + s.label + ' · ' + published + '] ' + title
          + '\n  Authors: ' + (authors || 'Unknown')
          + '\n  Abstract: ' + summary.replace(/\n/g, ' ').substring(0, 300) + '...'
        );
      }
    });
  });
}


// ============================================================
// SECTION 7 — MediaStack: Cybersecurity News Articles
// ============================================================
function fetchMediaStack(body) {
  appendSectionHeader(body, '7 · MediaStack — Cybersecurity News Articles');

  if (CONFIG.MEDIASTACK_KEY === 'ae*****************') {
    appendItem(body, '⚠ MediaStack key not set — paste your key into CONFIG.MEDIASTACK_KEY at the top of the script.');
    return;
  }

  const msUrl = 'https://api.mediastack.com/v1/news'
    + '?access_key=' + CONFIG.MEDIASTACK_KEY
    + '&keywords=cybersecurity,hacking,ransomware,malware,data breach,zero day'
    + '&languages=en'
    + '&limit=20'
    + '&sort=published_desc';

  const msRaw = safeGet(msUrl);

  if (!msRaw) {
    appendItem(body, '⚠ Could not reach MediaStack. Check your key at mediastack.com.');
    return;
  }

  let msData;
  try { msData = JSON.parse(msRaw); } catch(e) {
    appendItem(body, '⚠ MediaStack parse error: ' + e.message);
    return;
  }

  if (msData.error) {
    appendItem(body, '⚠ MediaStack error [' + msData.error.code + ']: ' + msData.error.message);
    return;
  }

  const articles = msData.data || [];
  if (articles.length === 0) {
    appendItem(body, 'No MediaStack articles returned for this period.');
    return;
  }

  articles.forEach(function(a) {
    const source = a.source        || 'Unknown';
    const title  = a.title         || 'Untitled';
    const desc   = (a.description  || '').replace(/\n/g, ' ').substring(0, 180);
    const date   = (a.published_at || '').substring(0, 10);
    const url    = a.url           || '';
    appendItem(body,
      '[' + source + ' · ' + date + '] ' + title
      + (desc ? '\n  ' + desc : '')
      + (url  ? '\n  ' + url  : '')
    );
  });
}


// ============================================================
// SECTION 8 — YouTube: Cybersecurity Videos
// ============================================================
function fetchYouTube(body) {
  appendSectionHeader(body, '8 · YouTube — Cybersecurity Videos & Conference Talks');

  if (!CONFIG.GOOGLE_API_KEY || CONFIG.GOOGLE_API_KEY === 'YOUR_NEW_GOOGLE_API_KEY') {
    appendItem(body, '⚠ Google API key not set. Create one at console.cloud.google.com and enable YouTube Data API v3.');
    return;
  }

  const ninetyDaysAgo = new Date();
  ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90);
  const publishedAfter = ninetyDaysAgo.toISOString();

  const searches = [
    { q: 'cyber threat intelligence briefing 2026',     label: 'Threat Intel' },
    { q: 'DEF CON Black Hat 2025 talk presentation',    label: 'Conference' },
    { q: 'malware analysis reverse engineering 2025',    label: 'Malware' },
    { q: 'incident response SOC walkthrough 2025 2026', label: 'Incident Response' },
    { q: 'cybersecurity news weekly briefing 2026',     label: 'News Roundup' },
  ];

  const blockWords = [
    'hiring', 'freshers', 'salary', 'job opening', 'placement',
    'recruitment', 'course promo', 'get rich', 'beginners guide',
    'roadmap', '5 levels', '8 minutes', 'anyone can',
    'your phone is hacked', 'dark web explained', 'wifi hack',
    'spy on', 'track your', 'spy and track', '$50 device',
    'ethical hacker explains', 'top 10 hacks', 'every level',
    'full course', 'bootcamp',
  ];

  let totalResults = 0;

  searches.forEach(function(s) {
    if (totalResults >= CONFIG.MAX_YOUTUBE_RESULTS) return;

    const url = 'https://www.googleapis.com/youtube/v3/search'
      + '?part=snippet'
      + '&q=' + encodeURIComponent(s.q)
      + '&type=video'
      + '&videoDuration=medium'
      + '&relevanceLanguage=en'
      + '&order=date'
      + '&publishedAfter=' + publishedAfter
      + '&maxResults=5'
      + '&key=' + CONFIG.GOOGLE_API_KEY;

    const raw = safeGet(url);
    if (!raw) return;

    let data;
    try { data = JSON.parse(raw); } catch(e) { return; }

    if (data.error) {
      appendItem(body, '⚠ YouTube API error: ' + data.error.message);
      return;
    }

    (data.items || []).forEach(function(item) {
      if (totalResults >= CONFIG.MAX_YOUTUBE_RESULTS) return;

      const snip    = item.snippet || {};
      const title   = snip.title        || 'Untitled';
      const channel = snip.channelTitle || 'Unknown';
      const pub     = (snip.publishedAt || '').substring(0, 10);
      const desc    = (snip.description || '').replace(/\n/g, ' ').substring(0, 160);
      const videoId = (item.id && item.id.videoId) ? item.id.videoId : '';
      const ytUrl   = videoId ? 'https://youtu.be/' + videoId : '';

      const titleLower = title.toLowerCase();
      const isBlocked  = blockWords.some(function(w){ return titleLower.indexOf(w) !== -1; });
      if (isBlocked || title.length < 15) return;

      appendItem(body,
        '[YouTube · ' + s.label + ' · ' + pub + '] "' + title + '" by ' + channel
        + '\n  ' + desc
        + (ytUrl ? '\n  ' + ytUrl : '')
      );
      totalResults++;
    });
  });

  if (totalResults === 0) {
    appendItem(body, '⚠ No relevant YouTube videos found. Check YouTube Data API v3 is enabled in Google Cloud Console.');
  }
}


// ============================================================
// SECTION 9 — MITRE ATT&CK via TAXII 2.1
// ============================================================
function fetchMitreAttack(body) {
  appendSectionHeader(body, '9 · MITRE ATT&CK — Tactics, Techniques & Procedures');

  const baseUrl      = 'https://attack-taxii.mitre.org/api/v21/';
  const taxiiHeaders = { 'Accept': 'application/taxii+json;version=2.1' };

  const collectionsRaw = safeGet(baseUrl + 'collections/', taxiiHeaders);
  if (!collectionsRaw) { appendItem(body, '⚠ Could not reach MITRE TAXII server.'); return; }

  let collections;
  try { collections = JSON.parse(collectionsRaw); } catch(e) {
    appendItem(body, '⚠ MITRE parse error: ' + e.message); return;
  }

  const enterprise = (collections.collections || []).find(function(c) {
    return c.title && c.title.toLowerCase().includes('enterprise');
  });

  if (!enterprise) { appendItem(body, '⚠ Enterprise ATT&CK collection not found.'); return; }
  appendItem(body, 'Collection: ' + enterprise.title);

  const objectsRaw = safeGet(
    baseUrl + 'collections/' + enterprise.id + '/objects/?match[type]=attack-pattern&limit=20',
    taxiiHeaders
  );

  if (!objectsRaw) { appendItem(body, '⚠ Could not fetch ATT&CK techniques.'); return; }

  let objects;
  try { objects = JSON.parse(objectsRaw); } catch(e) {
    appendItem(body, '⚠ ATT&CK parse error: ' + e.message); return;
  }

  (objects.objects || []).slice(0, 20).forEach(function(obj) {
    const name    = obj.name || 'Unnamed';
    const desc    = (obj.description || '').replace(/\n/g, ' ').substring(0, 250);
    const tactics = (obj.kill_chain_phases || []).map(function(p){ return p.phase_name; }).join(', ');
    const extRef  = (obj.external_references || []).find(function(r){ return r.source_name === 'mitre-attack'; });
    const extId   = extRef ? extRef.external_id : '';
    appendItem(body,
      '[' + (extId || 'ATT&CK') + ' · ' + (tactics || 'no tactic') + '] '
      + name + '\n  ' + desc
    );
  });
}


// ============================================================
// SECTION 10 — Hacker News: Community Security Stories
// ============================================================
function fetchHackerNews(body) {
  appendSectionHeader(body, '10 · Hacker News — Community Cybersecurity Stories');

  const hnRaw = safeGet('https://hacker-news.firebaseio.com/v0/topstories.json');
  if (!hnRaw) {
    appendItem(body, '⚠ Could not reach Hacker News.');
    return;
  }

  let ids;
  try { ids = JSON.parse(hnRaw).slice(0, 150); } catch(e) {
    appendItem(body, '⚠ Hacker News parse error: ' + e.message);
    return;
  }

  const cyberKeywords = [
    'security', 'hack', 'breach', 'malware', 'ransomware',
    'vulnerability', 'exploit', 'cyber', 'phish', 'cve',
    'zero-day', 'zero day', 'botnet', 'spyware', 'trojan',
    'attack', 'encryption', 'firewall', 'backdoor',
    'surveillance', 'apt', 'nation state', 'data leak'
  ];

  let cyberCount = 0;

  for (let i = 0; i < ids.length && cyberCount < 12; i++) {
    const storyRaw = safeGet('https://hacker-news.firebaseio.com/v0/item/' + ids[i] + '.json');
    if (!storyRaw) continue;

    let story;
    try { story = JSON.parse(storyRaw); } catch(e) { continue; }

    const titleLower = (story.title || '').toLowerCase();
    const isCyber = cyberKeywords.some(function(kw){ return titleLower.indexOf(kw) !== -1; });

    if (isCyber && story.title) {
      const date = story.time
        ? new Date(story.time * 1000).toISOString().substring(0, 10)
        : 'Unknown date';
      appendItem(body,
        '[Hacker News · ' + date + '] ' + story.title
        + (story.score       ? ' — ' + story.score + ' pts'            : '')
        + (story.descendants ? ' · ' + story.descendants + ' comments' : '')
        + (story.url         ? '\n  ' + story.url                      : '')
      );
      cyberCount++;
    }
    Utilities.sleep(80);
  }

  if (cyberCount === 0) {
    appendItem(body, 'No cybersecurity stories found in Hacker News top 150 right now.');
  }
}


// ============================================================
// UTILITY FUNCTIONS
// ============================================================

function getOrCreateDoc(name) {
  const files = DriveApp.getFilesByName(name);
  if (files.hasNext()) return DocumentApp.openById(files.next().getId());
  return DocumentApp.create(name);
}

function appendSectionHeader(body, title) {
  body.appendParagraph('').setHeading(DocumentApp.ParagraphHeading.NORMAL);
  const p = body.appendParagraph(title);
  p.setHeading(DocumentApp.ParagraphHeading.HEADING2);
  p.setBold(true);
}

function appendItem(body, text) {
  body.appendParagraph('• ' + text).setHeading(DocumentApp.ParagraphHeading.NORMAL);
}

function safeGet(url, headers) {
  try {
    const options = { muteHttpExceptions: true, headers: headers || {} };
    const response = UrlFetchApp.fetch(url, options);
    const code = response.getResponseCode();
    if (code === 200) return response.getContentText();
    Logger.log('HTTP ' + code + ' for: ' + url);
    return null;
  } catch(e) {
    Logger.log('Exception fetching ' + url + ': ' + e.message);
    return null;
  }
}

function getNistDate(daysAgo) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().replace('Z', '').substring(0, 23);
}

function getSimpleDate(daysAgo) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().substring(0, 10);
}

function getSeverityLabel(score) {
  if (score >= 9.0) return '🔴 CRITICAL';
  if (score >= 7.0) return '🟠 HIGH';
  if (score >= 4.0) return '🟡 MEDIUM';
  return '🟢 LOW';
}

function decodeHtmlEntities(text) {
  return text
    .replace(/&lt;/g,   '<')
    .replace(/&gt;/g,   '>')
    .replace(/&amp;/g,  '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g,  "'")
    .replace(/&nbsp;/g, ' ');
}

function stripHtmlTags(text) {
  return text.replace(/<[^>]+>/g, '');
}


// ============================================================
// TRIGGER — Run createDailyTrigger() ONCE to automate
// ============================================================
function createDailyTrigger() {
  ScriptApp.getProjectTriggers().forEach(function(t) {
    ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger('runCyberSecAggregator')
    .timeBased()
    .everyDays(1)
    .atHour(6)
    .create();
  Logger.log('✅ Daily trigger set for 6am Sydney time.');
}


// ============================================================
// TEST — Swap function name inside to test any single section
// ============================================================
function testSingleSection() {
  const doc  = getOrCreateDoc('CyberSec TEST');
  const body = doc.getBody();
  body.clear();
  body.appendParagraph('TEST RUN — ' + new Date().toLocaleString());

  fetchMediaStack(body); // ← swap to test any section

  doc.saveAndClose();
  Logger.log('Test complete: ' + doc.getUrl());
}